### ISSUE TITLE
大佬，再打扰一下。没有找到修改密码和重置密码的API

### ISSUE THREAD

**Issue by LipYoung** [lincanbin/Carbon-Forum-API-Documentation#5]
如题

**Comment by lincanbin** [comment]
这两个目前还没提供API。
低频操作放网页上了。

**Comment by LipYoung** [comment]
😭 😭

**Comment by LipYoung** [comment]
@lincanbin  尊敬的大佬能不能给一下 移动端的重置密码和修改密码的 路由。我访问 `/forget` 不能正常响应。移动端的 `m.XXX.com`

**Comment by lincanbin** [comment]
移动端也没这个路由，高频操作只有PC端有。

**Comment by LipYoung** [comment]
恩恩，也够目前测试使用了。感谢大佬的回复

**Comment by LipYoung** [comment]
我想用移动端的浏览器访问PC端的网页 `/settings#settings4` 和 `/forgo` 来让用户在网页上进行修改密码和重置密码的操作，但是网页会自动跳转到 移动端样式且进入首页。

导致没有办法达到修改密码和重置密码的操作，现在的解决办法就是让用户自己登陆PC的浏览器来进行修改密码和重置密码，先这么处理了只能。

如果有办法可以简单修改下就让用户在移动端访问PC端的网页的话，请大佬告知一下，没有就算了~ 万分感谢了

**Comment by lincanbin** [comment]
没有简单的方法，只能等我有空去适配移动端的模板了。
