### ISSUE TITLE
调用 /login 接口，服务器返回403错误

### ISSUE THREAD

**Issue by LipYoung** [lincanbin/Carbon-Forum-API-Documentation#6]
首先调用一次`/seccode`接口，然后将cookie记录下来
```
这是获取到的cookie 不知道是否正确
[<NSHTTPCookie
	version:0
	name:PHPSESSID
	value:6negvcfmf9i73pg3f1porbmkv0
	expiresDate:'(null)'
	created:'2019-08-01 10:54:24 +0000'
	sessionOnly:TRUE
	domain:www.crowd-writing.club
	partition:none
	sameSite:none
	path:/
	isSecure:FALSE
 path:"/" isSecure:FALSE>]
```
然后将这些数据和用户名，密码验证码数字一起调用 `/login`接口。
服务器返回了403错误。应该怎么处理或者检查呢？

**Comment by LipYoung** [comment]
是不是应该将 set-cookie 的值保存下来，用来放到请求 `/login`的请求头里面？

```
- key : "Set-Cookie"
- value : "PHPSESSID=aolod1f5otqrh5ph3tpv2tdtm6; path=/"
```

**Comment by LipYoung** [comment]
![image](https://user-images.githubusercontent.com/15086314/62289084-625c0980-b490-11e9-9a2b-af38a4ff2100.png)

这张图片，是我用postman调用验证码接口后查看cookie的截图。postman显示请求验证码的请求没有cookie内容。我用浏览器调用的时候也是没有响应cookie

**Comment by LipYoung** [comment]
![image](https://user-images.githubusercontent.com/15086314/62289603-bb786d00-b491-11e9-9c76-e2be5cf70400.png)

浏览器调用验证码接口的cookie 截图

**Comment by lincanbin** [comment]
是的，把 set-cookie 的值保存下来，用来放到请求 /login的请求头里面。

**Comment by LipYoung** [comment]
好的。我先试一试。thx

**Comment by LipYoung** [comment]
将 set-cookie 的值保存下来，用来放到请求 `/login`的请求头里面

```
- key : "Set-Cookie"
- value : "PHPSESSID=aolod1f5otqrh5ph3tpv2tdtm6; path=/"
```

然后 Duang 的一声就搞定了~
